language: php

php:
    - 7.2
    - 7.3
    - 7.4
    - 8.0snapshot

before_script:
    - composer self-update
    - composer install --dev

script:
    - mkdir -p build/logs
    - make sniff test

after_script:
    - php vendor/bin/coveralls -v
