blank_issues_enabled: true
contact_links:
  - name: 🔒 Security Issue
    url: https://github.com/tomaj/prepositioner/security/policy
    about: Please report security vulnerabilities through our Security Policy
